2018-03-28 13:22:48 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.bloomberg.com/search?query=Amazon%20> (referer: None)
Traceback (most recent call last):
  File "c:\users\owner\documents\codingdojo\python\django\django-venv\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\users\owner\documents\codingdojo\python\django\django-venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\users\owner\documents\codingdojo\python\django\django-venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\users\owner\documents\codingdojo\python\django\django-venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\owner\documents\codingdojo\python\django\django-venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "stockBot\spiders\bloomberg.py", line 109, in parse3
    new_h+=str(h)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 5: ordinal not in range(128)
